version: '3.7'

services:
  redis-master:
    image: kumojin/redis:5
    # volumes:
    #   - redis-data:/data
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints:
          # - node.role == worker
          - node.labels.redis-master == true
    networks:
      - redis

  redis-slave:
    image: kumojin/redis:5
    command: --slaveof redis-master 6379
    # volumes:
    #   - redis-data:/data
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints:
          # - node.role == worker
          - node.labels.redis-replica == true
    networks:
      - redis

  redis-sentinel:
    image: kumojin/redis-sentinel:5
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          # - node.role == worker
          - node.labels.redis-sentinel == true
    environment:
      - "SENTINEL_MASTER_IP=redis-master"
    networks:
      - redis

networks:
  redis:
    driver: overlay

volumes:
  redis-data:
