version: '3.7'

services:
  redis-master:
    image: redis
    volumes:
      - redis-data:/data
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints:
          - node.role == worker
          - node.labels.redistype == master
    networks:
      host:
  redis-slave:
    image: redis
    command: redis-server --slaveof redis-master 6379
    volumes:
      - redis-data:/data
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints:
          - node.role == worker
          - node.labels.redistype == replica
    networks:
      host:
  redis-sentinel:
    image: kumojin/redis:sentinel
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
          - node.labels.app == redis
    environment:
      - "SENTINEL_MASTER_IP=redis-master"
    networks:
      host:

networks:
  host:
    external: true

volumes:
  redis-data:
